branch-defaults:
  default:
    environment: explora-server
environment-defaults:
  explora-server:
    branch: null
    repository: null
global:
  application_name: datashark
  default_ec2_keyname: neel-ec2
  default_platform: 64bit Amazon Linux 2018.03 v2.8.3 running Python 3.4
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
