version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - uname -a
      - apt-get update
      - apt-get upgrade
      - apt-get install docker-engine -y
      - service docker start
      - docker run hello-world
      - pip install --upgrade awscli
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker run $IMAGE_REPO_NAME:$IMAGE_TAG