version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt
artifacts:
  files:
    - '**/*'
  # build:
  #   commands:
  #   - python server.py


  